return {
  {
    "WhoIsSethDaniel/mason-tool-installer.nvim",
    opts = {
      ensure_installed = {
        { "zsh-lsp", auto_update = true },
        {
          "gopls",
          condition = function() return vim.fn.executable "go" == 1 end,
        },
        {
          "delve",
          condition = function() return vim.fn.executable "go" == 1 end,
        },
        "lua-language-server",
        "stylua",
        "gofumpt",
        "golines",
        "gomodifytags",
        "gotests",
        "impl",
        "json-to-struct",
        "misspell",
        "revive",
        "shellcheck",
        "shfmt",
        "typescript-language-server",
        "prisma-language-server",
        "biome",
        "astro-language-server",
        "html-lsp",
        "tailwindcss-language-server",
        "css-lsp",
        "css-variables-language-server",
        "cssmodules-language-server",
        "stylelint-lsp",
        "json-lsp",
        "dockerfile-language-server",
        "docker-compose-language-service",
        "terraform-ls",
        "yaml-language-server",
        -- "marksman",
        -- "mdx-analyzer",
        "cspell-lsp",
        "typos-lsp",
        "gh-actions-language-server",
        "markdown-oxide",
        "vtsls",
        "js-debug-adapter",
        "codelldb",
        "oxlint",
        "oxfmt",
      },
    },
  },
  {
    "mason-org/mason.nvim",
    opts = {
      registries = {
        "github:mason-org/mason-registry",
        "github:Crashdummyy/mason-registry",
      },
      ui = {
        icons = {
          package_installed = "✓",
          package_pending = "➜",
          package_uninstalled = "✗",
        },
      },
    },
  },
}
